// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADSUh2zxEyvdSvIdXycYmyOL7Wb0IW4LI',
    appId: '1:201395359702:web:e96af8ce0e06820d4b5e77',
    messagingSenderId: '201395359702',
    projectId: 'eventify001',
    authDomain: 'eventify001.firebaseapp.com',
    storageBucket: 'eventify001.firebasestorage.app',
    measurementId: 'G-8PEE6ELQF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEOlOtLS20ON6FR3cwS8KJeYAJoYVxicA',
    appId: '1:201395359702:android:8c0dc310449ee7314b5e77',
    messagingSenderId: '201395359702',
    projectId: 'eventify001',
    storageBucket: 'eventify001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_y-NM8vTvPXtMTZecSeoQgoKIK3PYPpQ',
    appId: '1:201395359702:ios:aaffa86873f181004b5e77',
    messagingSenderId: '201395359702',
    projectId: 'eventify001',
    storageBucket: 'eventify001.firebasestorage.app',
    iosBundleId: 'com.example.eventify001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_y-NM8vTvPXtMTZecSeoQgoKIK3PYPpQ',
    appId: '1:201395359702:ios:aaffa86873f181004b5e77',
    messagingSenderId: '201395359702',
    projectId: 'eventify001',
    storageBucket: 'eventify001.firebasestorage.app',
    iosBundleId: 'com.example.eventify001',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADSUh2zxEyvdSvIdXycYmyOL7Wb0IW4LI',
    appId: '1:201395359702:web:8c6c7c852798bbc24b5e77',
    messagingSenderId: '201395359702',
    projectId: 'eventify001',
    authDomain: 'eventify001.firebaseapp.com',
    storageBucket: 'eventify001.firebasestorage.app',
    measurementId: 'G-S5EBV5V9HT',
  );
}
